version: "3.8"

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000
  POSTGRES_PASSWORD: postgrespassword
  POSTGRES_USER: postgresuser
  POSTGRES_DB: postgresdb

services:
  database:
    image: postgres:13.0
    build: ./db
    restart: always
    ports:
      - 5432:5432
    environment:
      <<: *common-variables
      listen_addresses: "*"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  server:
    build: ./server
    depends_on:
      - database
    expose:
      - 8000
    environment:
      <<: *common-variables
      POSTGRES_HOST_IP: database
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - database
    command: npm start
  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    stdin_open: true
    command: npm start
